# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: "Predecir para proteger: Un enfoque de Machine Learning en casos de Violencia Basada en Género en Colombia (2018–2023)"
author: "Kevin Jaimes"
logo: logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: informe.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://kevinjaimes17.github.io/Proyecto_ML_en_VBG/notebooks/EDA.html  # Online location of your bo…
